# Generated by Django 2.0.13 on 2019-10-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20181115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='surcharge_excl_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Surcharge (excl. tax)'),
        ),
        migrations.AddField(
            model_name='order',
            name='surcharge_incl_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Surcharge (inc. tax)'),
        ),
    ]
