# Generated by Django 2.1 on 2019-06-17 17:44

from django.db import migrations


def migrate_product_options(apps, schema_editor):
    """
    Migrate product Option.type field to required
    Set Option.type='text'
    """
    Option = apps.get_model('catalogue', 'Option')
    for option in Option.objects.all():
        if option.type == "Required":
            option.required = True
        option.type = 'text'
        option.save()


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_option_required'),
    ]

    operations = [
        migrations.RunPython(migrate_product_options, migrations.RunPython.noop),
    ]
